Translate structs to maps
brainn-co/xcribe pull request #51
Opened 2020-09-25 21:16 UTC by antedeguemon

## Motivation

This PR is an attempt to fix xcribe issues with structs:
- #28: Xcribe breaks when Date struct is given as params
- #49: Support Plug.Upload struct

## Proposed solution

1. When a struct implements the protocol `String.Chars`, apply `to_string/1`. This implementation check is done using `Protocol.assert_impl!/2` with a try/catch block (`assert_impl?` does not exist :cry: ).
2. When a struct doesn't implement `String.Chars` , apply `Map.from_struct/1` to it and remove struct metadata.

2020-09-26 01:05 UTC, brosquinha approved these changes

2020-09-26 14:19 UTC, thiamsantos approved these changes

2020-09-27 14:38 UTC, thiamsantos commented on lib/xcribe/json_schema.ex
> +    try do
```
defp stringy?(value) do
  case String.Chars.impl_for(value) do
    nil -> false
    _ -> true
  end
end
```
@antedeguemon :nail_care:

2020-09-28 15:17 UTC, Danielwsx64 requested changes
@antedeguemon first of all, tks for the PR.

I think the proposed solution can bring us new issues.
Eg: In the case of someone implements the `chars` protocol for some struct and Xcribe starts documenting it on the wrong way. Some printable pattern that is not representative in json schema on JsonAPI.

Other point, I wasn't handle this yet, but it can be a good moment to add the `format` key for date and datetime as specified in https://swagger.io/specification/#data-types

Something like:

```
%{
  "last_login" => %{type: "string", format: "date", example: "2020-09-01"}
}
```

A sugestion (if you aggree in doing that) is add an implementation of `format_for/1` for native date/datetime Elixir implementations (Date, DateTime and NaiveDateTime) and check the data format before call the private function `schema_object_for`, so you can use the result in `schema_object_for` pattern matching, instead of the guards `is_map/1` and `is_list/1`.

You mentioned the issue #49 but I'm not shure if was your intention solve both in the same PR. For files upload we have this specification https://swagger.io/specification/#media-type-object. That means we can't represent `Plug.Upload` struct as a json schema (Because the API user dont send it to us, it is added by Phoenix to give us access to uploaded file). We should represente the file as a new media type.

wdyt?

2020-09-28 20:52 UTC, antedeguemon commented
> I think the proposed solution can bring us new issues.
> Eg: In the case of someone implements the `chars` protocol for some struct and Xcribe starts documenting it on the wrong way. Some printable pattern that is not representative in json schema on JsonAPI.

Yeah, that may happen. :grimacing: 


> Other point, I wasn't handle this yet, but it can be a good moment to add the `format` key for date and datetime as specified in https://swagger.io/specification/#data-types

That would be awesome. I am not sure how to deal with `format` in json-schema yet, but I am going to take a look at that. Seems [that it specifies date and datetimes](https://json-schema.org/understanding-json-schema/reference/string.html#dates-and-times)), which will be helpful.

> A sugestion (if you aggree in doing that) is add an implementation of `format_for/1` for native date/datetime Elixir implementations (Date, DateTime and NaiveDateTime) and check the data format before call the private function `schema_object_for`, so you can use the result in `schema_object_for` pattern matching, instead of the guards `is_map/1` and `is_list/1`.

Of course! Thanks for the review, I will try to find a better way to deal with #28 that does not cause other hasle.

> You mentioned the issue #49 but I'm not shure if was your intention solve both in the same PR. For files upload we have this specification https://swagger.io/specification/#media-type-object. That means we can't represent `Plug.Upload` struct as a json schema (Because the API user dont send it to us, it is added by Phoenix to give us access to uploaded file). We should represente the file as a new media type.

Sooo... My original intention was to fix #28, but #49 was "fixed" as a collateral effect. I will change this PR description to specify that it only solves #28.

Thanks @Danielwsx64!

2020-09-28 21:11 UTC, thiamsantos commented
> I think the proposed solution can bring us new issues.
Eg: In the case of someone implements the chars protocol for some struct and Xcribe starts documenting it on the wrong way. Some printable pattern that is not representative in json schema on JsonAPI.

@Danielwsx64 @antedeguemon I don't know if this should be a case where we care about.

The documentation generated by xcribe should reflect what the API will receive. A user cannot pass a struct via a HTTP request. If we do that in a test, we are passing a invalid value at some level. Running the chars protocol seems to be a reasonable approach, as it essentially mimics what the plug is doing, in order to avoid xcribe from breaking.

2020-10-02 12:40 UTC, Danielwsx64 commented
> The documentation generated by xcribe should reflect what the API will receive. A user cannot pass a struct via a HTTP request. If we do that in a test, we are passing a invalid value at some level. Running the chars protocol seems to be a reasonable approach, as it essentially mimics what the plug is doing, in order to avoid xcribe from breaking.

@thiamsantos  I agree with you. The parameters putted into a `Plug.Conn` during the tests should be 

> > I think the proposed solution can bring us new issues.
> > Eg: In the case of someone implements the chars protocol for some struct and Xcribe starts documenting it on the wrong way. Some printable pattern that is not representative in json schema on JsonAPI.
> 
> @Danielwsx64 @antedeguemon I don't know if this should be a case where we care about.
> 
> The documentation generated by xcribe should reflect what the API will receive. A user cannot pass a struct via a HTTP request. If we do that in a test, we are passing a invalid value at some level. Running the chars protocol seems to be a reasonable approach, as it essentially mimics what the plug is doing, in order to avoid xcribe from breaking.

@thiamsantos  I agree with you. The parameters putted into a `Plug.Conn` during the tests should be valid http parameters format. But the issue is about the case you sad "If we do that in a test, we are passing a invalid value at some level". Some one passed a `%Date{}` as a request parameter. So if the idea is Xcribe handle that, we must avoid mess up other kind of structs, since we accept structs as request parameters.

Other aproach is raise some error when a `Plug.Conn` get some invalid parameters (as data structs and others) and show it friendly #36 . This way we can instruct the dev to fix the test setup.

I'm ok with both aproachs, but if we choose Xcribe handling structs, I prefer don't depende of `Chars` protocol to do that.

WDYT folks?

2020-10-03 14:18 UTC, thiamsantos commented
> Other aproach is raise some error when a Plug.Conn get some invalid parameters (as data structs and others) and show it friendly #36 . This way we can instruct the dev to fix the test setup.

@Danielwsx64 That seems to be a really reasonable approach, in that way we avoid crashes in xcribe without making any kind of assumptions about the params. It would fix #28 . WDYT @antedeguemon ?


About #49 do you have any ideas on how to handle that? @Danielwsx64 Should we add a special support for it?

2020-10-07 03:53 UTC, antedeguemon commented
@Danielwsx64 @thiamsantos folks, I am closing this PR in order to not pollute history because solution has changed.

2020-10-07 03:53 UTC, closed without merging